# Site
repository: kurtnheiss/kurtnheiss.io
favicon: images/favicon.ico

# Personal info
name: Kurt N. Heiss
# title: Project Management/Content Development
email: kurtnheiss@gmail.com
## website: www.github.com/kurtnheiss/kurtnheiss.io

# Social links
twitter_username: kurtnheiss
github_username:  kurtnheiss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kurt.n.heiss
linkedin_username: kurtnheiss
# pinterest_username: jekyll
youtube_username: kurtnheiss
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kurt 
  
  I am a business professional with skills and interest in information development, marketing, and management. I have extensive and 
  varied experience working at both established Silicon Valley tech giants as well as startups.
  
  Currently based in San Jose via stops in San Francisco, Orange County, and Seattle. I grew up in the Los Angeles area. 
  
  An alumnus of Santa Clara University and the University of Washington.

  Intrigued by strategy, organization, design, writing, art, productivity hacks, meditation, cooking, workouts, classical and 
  metal music, IDM, and thought provoking conversation.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  In my free time, I like to learn new skills, hone my artistic interests, and exercise. 
  
  Right now I am taking front-end web developer coursework through [Free Code Camp](https://www.freecodecamp.org/kurtnheiss).
  
  Some of my other interests and hobbies are:
  
   - Surfing
   - Swimming 
   - Hiking
   - Writing screenplays
   - Clay and papier mache sculpting
   - Trying different techniques on the guitar and bass
   - Returning to study of the cello
   - Learning German
   - [Reading](https://www.goodreads.com/user/show/5016817-kurt-heiss)
   - Vegetarian cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
